language: node_js
node_js:
  - 12.16.3

branches:
  only:
    - /.*/

cache:
  yarn: true
#  directories:
#    - ./backend/node_modules
#    - ./frontend/host-app/node_modules
#    - ./frontend/guest-app/node_modules
#    - ./frontend/main-app/node_modules

install:
  - yarn install

jobs:
  include:
    - stage: test
      name: backend node
      script:
        - yarn install:backend
        - yarn test:backend

    - name: frontend host-app
      script:
        - yarn install:frontend:host-app
        - yarn test:frontend:host-app

    - name: frontend guest-app
      script:
        - yarn install:frontend:guest-app
        - yarn test:frontend:guest-app

    - name: frontend main-app
      script:
        - yarn install:frontend:main-app
        - yarn test:frontend:main-app

    - name: backend spring
      language: java
      script:
        - cd ./backend/spring
        - gradle --console=plain build

    - stage: build
      script:
        - yarn install:all
        - yarn build
