export const POLL_ACTION_TYPE_VOTE = "VOTE";
export const POLL_ACTION_TYPE_RATE = "RATE";
export const POLL_ACTION_TYPE_CANCEL_RATING = "CANCEL_RATING";
export const POLL_ACTION_TYPE_SOMEONE_RATE = "SOMEONE_RATE";
export const POLL_ACTION_TYPE_SOMEONE_VOTE = "SOMEONE_VOTE";
export const POLL_ACTION_TYPE_NOTIFY_CLOSE = "NOTIFY_CLOSE";
export const POLL_ACTION_TYPE_NOTIFY_OPEN = "NOTIFY_OPEN";
